# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SCNR_main.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 992)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Button_stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_stop.sizePolicy().hasHeightForWidth())
        self.Button_stop.setSizePolicy(sizePolicy)
        self.Button_stop.setObjectName("Button_stop")
        self.gridLayout_2.addWidget(self.Button_stop, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 2, 1, 1)
        self.CheckBox_correct = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckBox_correct.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CheckBox_correct.setObjectName("CheckBox_correct")
        self.gridLayout_2.addWidget(self.CheckBox_correct, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 12, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Button_stepup = QtWidgets.QPushButton(self.centralwidget)
        self.Button_stepup.setObjectName("Button_stepup")
        self.gridLayout_3.addWidget(self.Button_stepup, 0, 0, 1, 1)
        self.Button_stepdown = QtWidgets.QPushButton(self.centralwidget)
        self.Button_stepdown.setObjectName("Button_stepdown")
        self.gridLayout_3.addWidget(self.Button_stepdown, 0, 2, 1, 1)
        self.label_stepsize = QtWidgets.QLabel(self.centralwidget)
        self.label_stepsize.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stepsize.setObjectName("label_stepsize")
        self.gridLayout_3.addWidget(self.label_stepsize, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 8, 2, 1, 1)
        self.Button_searchmax = QtWidgets.QPushButton(self.centralwidget)
        self.Button_searchmax.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Button_searchmax.setObjectName("Button_searchmax")
        self.gridLayout_2.addWidget(self.Button_searchmax, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 2, 1, 1)
        self.plotwidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotwidget.sizePolicy().hasHeightForWidth())
        self.plotwidget.setSizePolicy(sizePolicy)
        self.plotwidget.setMinimumSize(QtCore.QSize(400, 400))
        self.plotwidget.setObjectName("plotwidget")
        self.gridLayout_2.addWidget(self.plotwidget, 0, 0, 13, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 90))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Button_xup = QtWidgets.QPushButton(self.frame_2)
        self.Button_xup.setGeometry(QtCore.QRect(10, 30, 50, 30))
        self.Button_xup.setObjectName("Button_xup")
        self.Button_xdown = QtWidgets.QPushButton(self.frame_2)
        self.Button_xdown.setGeometry(QtCore.QRect(110, 30, 50, 30))
        self.Button_xdown.setObjectName("Button_xdown")
        self.Button_yup = QtWidgets.QPushButton(self.frame_2)
        self.Button_yup.setGeometry(QtCore.QRect(60, 0, 50, 30))
        self.Button_yup.setObjectName("Button_yup")
        self.Button_ydown = QtWidgets.QPushButton(self.frame_2)
        self.Button_ydown.setGeometry(QtCore.QRect(60, 60, 50, 30))
        self.Button_ydown.setObjectName("Button_ydown")
        self.Button_zup = QtWidgets.QPushButton(self.frame_2)
        self.Button_zup.setGeometry(QtCore.QRect(190, 0, 50, 30))
        self.Button_zup.setObjectName("Button_zup")
        self.Button_zdown = QtWidgets.QPushButton(self.frame_2)
        self.Button_zdown.setGeometry(QtCore.QRect(190, 60, 50, 30))
        self.Button_zdown.setObjectName("Button_zdown")
        self.gridLayout_2.addWidget(self.frame_2, 6, 2, 1, 1)
        self.label_x = QtWidgets.QLabel(self.centralwidget)
        self.label_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x.setObjectName("label_x")
        self.gridLayout_2.addWidget(self.label_x, 9, 2, 1, 1)
        self.label_z = QtWidgets.QLabel(self.centralwidget)
        self.label_z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_z.setObjectName("label_z")
        self.gridLayout_2.addWidget(self.label_z, 11, 2, 1, 1)
        self.label_y = QtWidgets.QLabel(self.centralwidget)
        self.label_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_y.setObjectName("label_y")
        self.gridLayout_2.addWidget(self.label_y, 10, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2.addWidget(self.widget_3, 1, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(250, 550))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(0, 527))
        self.tab.setObjectName("tab")
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 241, 511))
        self.widget_2.setObjectName("widget_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 241, 511))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.formLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Button_live = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_live.setObjectName("Button_live")
        self.verticalLayout.addWidget(self.Button_live)
        self.line = QtWidgets.QFrame(self.formLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Button_aquire = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_aquire.setObjectName("Button_aquire")
        self.verticalLayout.addWidget(self.Button_aquire)
        self.Button_direction = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_direction.setObjectName("Button_direction")
        self.verticalLayout.addWidget(self.Button_direction)
        self.Button_dark = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_dark.setObjectName("Button_dark")
        self.verticalLayout.addWidget(self.Button_dark)
        self.Button_lamp = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_lamp.setObjectName("Button_lamp")
        self.verticalLayout.addWidget(self.Button_lamp)
        self.Button_regular = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_regular.setObjectName("Button_regular")
        self.verticalLayout.addWidget(self.Button_regular)
        self.Button_background = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_background.setObjectName("Button_background")
        self.verticalLayout.addWidget(self.Button_background)
        self.line_2 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Button_series = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_series.setObjectName("Button_series")
        self.verticalLayout.addWidget(self.Button_series)
        self.Button_save = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_save.setObjectName("Button_save")
        self.verticalLayout.addWidget(self.Button_save)
        self.Button_settings = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_settings.setObjectName("Button_settings")
        self.verticalLayout.addWidget(self.Button_settings)
        self.Button_reset = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_reset.setObjectName("Button_reset")
        self.verticalLayout.addWidget(self.Button_reset)
        self.Button_loaddark = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_loaddark.setObjectName("Button_loaddark")
        self.verticalLayout.addWidget(self.Button_loaddark)
        self.Button_loadlamp = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Button_loadlamp.setObjectName("Button_loadlamp")
        self.verticalLayout.addWidget(self.Button_loadlamp)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(0, 0, 241, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(100, 0))
        self.widget.setObjectName("widget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 241, 501))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gridLayoutWidget_3)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(5, 5, -1, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Button_addpos = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_addpos.sizePolicy().hasHeightForWidth())
        self.Button_addpos.setSizePolicy(sizePolicy)
        self.Button_addpos.setObjectName("Button_addpos")
        self.verticalLayout_2.addWidget(self.Button_addpos)
        self.Button_spangrid = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_spangrid.sizePolicy().hasHeightForWidth())
        self.Button_spangrid.setSizePolicy(sizePolicy)
        self.Button_spangrid.setObjectName("Button_spangrid")
        self.verticalLayout_2.addWidget(self.Button_spangrid)
        self.checkBox_search = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_search.setObjectName("checkBox_search")
        self.verticalLayout_2.addWidget(self.checkBox_search)
        self.checkBox_lockin = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_lockin.setObjectName("checkBox_lockin")
        self.verticalLayout_2.addWidget(self.checkBox_lockin)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 35))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(30, 0, 30, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        self.toolButton_3.setGeometry(QtCore.QRect(100, 0, 30, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon1)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(170, 0, 30, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon2)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_2.addWidget(self.frame)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(40, 265))
        self.tableWidget.setBaseSize(QtCore.QSize(100, 60))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("x")
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("y")
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(104)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.Button_scan = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_scan.sizePolicy().hasHeightForWidth())
        self.Button_scan.setSizePolicy(sizePolicy)
        self.Button_scan.setObjectName("Button_scan")
        self.verticalLayout_2.addWidget(self.Button_scan)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 2, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 13, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Button_live.clicked.connect(MainWindow.on_live_clicked)
        self.Button_aquire.clicked.connect(MainWindow.on_lockin_clicked)
        self.Button_direction.clicked.connect(MainWindow.on_direction_clicked)
        self.Button_dark.clicked.connect(MainWindow.on_dark_clicked)
        self.Button_lamp.clicked.connect(MainWindow.on_lamp_clicked)
        self.Button_regular.clicked.connect(MainWindow.on_mean_clicked)
        self.Button_background.clicked.connect(MainWindow.on_bg_clicked)
        self.Button_series.clicked.connect(MainWindow.on_series_clicked)
        self.Button_save.clicked.connect(MainWindow.on_save_clicked)
        self.Button_settings.clicked.connect(MainWindow.on_settings_clicked)
        self.Button_reset.clicked.connect(MainWindow.on_reset_clicked)
        self.Button_loaddark.clicked.connect(MainWindow.on_loaddark_clicked)
        self.Button_loadlamp.clicked.connect(MainWindow.on_loadlamp_clicked)
        self.Button_searchmax.clicked.connect(MainWindow.on_search_clicked)
        self.Button_stop.clicked.connect(MainWindow.on_stop_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.Button_spangrid)
        MainWindow.setTabOrder(self.Button_spangrid, self.Button_addpos)
        MainWindow.setTabOrder(self.Button_addpos, self.Button_dark)
        MainWindow.setTabOrder(self.Button_dark, self.Button_lamp)
        MainWindow.setTabOrder(self.Button_lamp, self.Button_stop)
        MainWindow.setTabOrder(self.Button_stop, self.Button_regular)
        MainWindow.setTabOrder(self.Button_regular, self.Button_background)
        MainWindow.setTabOrder(self.Button_background, self.Button_series)
        MainWindow.setTabOrder(self.Button_series, self.Button_save)
        MainWindow.setTabOrder(self.Button_save, self.Button_settings)
        MainWindow.setTabOrder(self.Button_settings, self.Button_reset)
        MainWindow.setTabOrder(self.Button_reset, self.Button_loaddark)
        MainWindow.setTabOrder(self.Button_loaddark, self.Button_direction)
        MainWindow.setTabOrder(self.Button_direction, self.Button_loadlamp)
        MainWindow.setTabOrder(self.Button_loadlamp, self.CheckBox_correct)
        MainWindow.setTabOrder(self.CheckBox_correct, self.Button_searchmax)
        MainWindow.setTabOrder(self.Button_searchmax, self.Button_stepup)
        MainWindow.setTabOrder(self.Button_stepup, self.Button_stepdown)
        MainWindow.setTabOrder(self.Button_stepdown, self.Button_aquire)
        MainWindow.setTabOrder(self.Button_aquire, self.Button_live)
        MainWindow.setTabOrder(self.Button_live, self.checkBox_search)
        MainWindow.setTabOrder(self.checkBox_search, self.checkBox_lockin)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SCNR"))
        self.Button_stop.setText(_translate("MainWindow", "Stop"))
        self.label_3.setText(_translate("MainWindow", "Stage Control"))
        self.CheckBox_correct.setText(_translate("MainWindow", "Correct Spectrum"))
        self.Button_stepup.setText(_translate("MainWindow", "+"))
        self.Button_stepdown.setText(_translate("MainWindow", "-"))
        self.label_stepsize.setText(_translate("MainWindow", "1.0"))
        self.Button_searchmax.setText(_translate("MainWindow", "Search Max"))
        self.label_4.setText(_translate("MainWindow", "Set Step Size [um]"))
        self.Button_xup.setText(_translate("MainWindow", "x+"))
        self.Button_xdown.setText(_translate("MainWindow", "x-"))
        self.Button_yup.setText(_translate("MainWindow", "y+"))
        self.Button_ydown.setText(_translate("MainWindow", "y-"))
        self.Button_zup.setText(_translate("MainWindow", "z+"))
        self.Button_zdown.setText(_translate("MainWindow", "z-"))
        self.label_x.setText(_translate("MainWindow", "X: 10.0"))
        self.label_z.setText(_translate("MainWindow", "Z: 10.0"))
        self.label_y.setText(_translate("MainWindow", "Y: 10.0"))
        self.Button_live.setText(_translate("MainWindow", "Liveview"))
        self.label.setText(_translate("MainWindow", "Lock-In Spectrum"))
        self.Button_aquire.setText(_translate("MainWindow", "Aquire Spectrum"))
        self.Button_direction.setText(_translate("MainWindow", "Set Direction"))
        self.Button_dark.setText(_translate("MainWindow", "Take Dark Spectrum"))
        self.Button_lamp.setText(_translate("MainWindow", "Take Lamp Spectrum"))
        self.Button_regular.setText(_translate("MainWindow", "Take Regular Spectrum"))
        self.Button_background.setText(_translate("MainWindow", "Take Background Spectrum"))
        self.label_2.setText(_translate("MainWindow", "Miscellaneous"))
        self.Button_series.setText(_translate("MainWindow", "Take Time Series"))
        self.Button_save.setText(_translate("MainWindow", "Save Data"))
        self.Button_settings.setText(_translate("MainWindow", "Settings"))
        self.Button_reset.setText(_translate("MainWindow", "Reset"))
        self.Button_loaddark.setText(_translate("MainWindow", "Load Dark Spectrum"))
        self.Button_loadlamp.setText(_translate("MainWindow", "Load Lamp Spectrum"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Spectra"))
        self.Button_addpos.setText(_translate("MainWindow", "Add Position to List"))
        self.Button_spangrid.setText(_translate("MainWindow", "Span Grid"))
        self.checkBox_search.setText(_translate("MainWindow", "Search Max"))
        self.checkBox_lockin.setText(_translate("MainWindow", "with Lock-In"))
        self.label_5.setText(_translate("MainWindow", "Scanning Positions"))
        self.toolButton_3.setText(_translate("MainWindow", "-"))
        self.toolButton.setText(_translate("MainWindow", "clear"))
        self.tableWidget.setSortingEnabled(False)
        self.Button_scan.setText(_translate("MainWindow", "Start Scan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Scanning"))

